"""Generate JSON / Markdown / annotated-PDF reports from verification results."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from hallucitation.verify import VerificationResult

_VERDICT_ICON = {
    "verified": "OK",
    "partial_match": "~",
    "mangled": "!",
    "hallucinated": "X",
}


def count_verdicts(results: list[VerificationResult]) -> dict[str, int]:
    counts = {"verified": 0, "partial_match": 0, "mangled": 0, "hallucinated": 0}
    for r in results:
        counts[r.verdict] = counts.get(r.verdict, 0) + 1
    return counts


def to_json(results: list[VerificationResult]) -> str:
    payload = {
        "summary": count_verdicts(results),
        "total": len(results),
        "results": [r.to_dict() for r in results],
    }
    return json.dumps(payload, indent=2, default=str)


def write_json(results: list[VerificationResult], path: str | Path) -> Path:
    path = Path(path)
    path.write_text(to_json(results))
    return path


def to_markdown(
    results: list[VerificationResult], *, source: str | None = None
) -> str:
    counts = count_verdicts(results)
    total = len(results)
    halluc = counts["hallucinated"]

    lines: list[str] = []
    lines.append("# Hallucitation Report")
    if source:
        lines.append(f"\n**Source:** `{source}`\n")
    lines.append(
        f"\n**{halluc} of {total}** references appear to be "
        f"**hallucinated** (no match in Crossref or OpenAlex)."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Verdict | Count |")
    lines.append("|---|---|")
    for verdict in ("verified", "partial_match", "mangled", "hallucinated"):
        lines.append(f"| {verdict} | {counts.get(verdict, 0)} |")
    lines.append("")

    if halluc:
        lines.append("## Suspected hallucinated references")
        lines.append("")
        for i, r in enumerate(results, 1):
            if r.verdict != "hallucinated":
                continue
            lines.append(f"**{i}.** {r.citation.raw}")
            lines.append(f"   - confidence: {r.confidence:.2f}")
            lines.append(f"   - notes: {r.notes}")
            lines.append("")

    lines.append("## All citations")
    lines.append("")
    lines.append("| # | Verdict | Conf | Title | First author | Year |")
    lines.append("|---|---|---|---|---|---|")
    for i, r in enumerate(results, 1):
        title = (r.citation.title or "?").replace("|", "\\|")[:80]
        author = (r.citation.first_author_surname or "?").replace("|", "\\|")
        year = r.citation.year or "?"
        lines.append(
            f"| {i} | {_VERDICT_ICON[r.verdict]} {r.verdict} | "
            f"{r.confidence:.2f} | {title} | {author} | {year} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by [hallucitation](https://github.com/Teyymour/Hallucitation). "
        "Not a substitute for human review."
    )
    return "\n".join(lines)


def write_markdown(
    results: list[VerificationResult],
    path: str | Path,
    *,
    source: str | None = None,
) -> Path:
    path = Path(path)
    path.write_text(to_markdown(results, source=source))
    return path


def annotate_pdf(
    source_pdf: str | Path,
    results: list[VerificationResult],
    output_pdf: str | Path,
) -> Path:
    """Write a new PDF with a cover-page summary listing hallucinated refs.

    We do not attempt true coordinate-based highlighting because reference
    text coordinates vary wildly per paper; instead we prepend a generated
    summary page to the original PDF using pypdf. This is robust and keeps
    the annotated artefact useful.
    """
    from io import BytesIO

    from pypdf import PdfReader, PdfWriter
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas

    output_pdf = Path(output_pdf)

    # Build a cover page in-memory.
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter
    y = height - 72

    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, y, "Hallucitation — Hallucinated Citation Report")
    y -= 28

    counts = count_verdicts(results)
    total = len(results)
    c.setFont("Helvetica", 11)
    c.drawString(
        72, y,
        f"{counts['hallucinated']} / {total} references flagged as hallucinated",
    )
    y -= 16
    c.drawString(
        72, y,
        f"Verified: {counts['verified']}  "
        f"Partial: {counts['partial_match']}  "
        f"Mangled: {counts['mangled']}",
    )
    y -= 24

    c.setFont("Helvetica-Bold", 12)
    c.drawString(72, y, "Suspect references:")
    y -= 16
    c.setFont("Helvetica", 9)

    for i, r in enumerate(results, 1):
        if r.verdict != "hallucinated":
            continue
        text = f"{i}. {r.citation.raw}"
        # Crude word-wrap.
        while text and y > 72:
            line = text[:100]
            text = text[100:]
            c.drawString(72, y, line)
            y -= 11
        y -= 4
        if y < 72:
            c.showPage()
            y = height - 72
            c.setFont("Helvetica", 9)

    c.showPage()
    c.save()
    buf.seek(0)

    writer = PdfWriter()
    cover_reader = PdfReader(buf)
    for page in cover_reader.pages:
        writer.add_page(page)
    src_reader = PdfReader(str(source_pdf))
    for page in src_reader.pages:
        writer.add_page(page)

    with open(output_pdf, "wb") as f:
        writer.write(f)
    return output_pdf
